### ISSUE TITLE
Asset library up to date? Which version do I have?

### ISSUE THREAD

**Issue by CitrusWire** [bitwes/Gut#265] opened 2021-01-12 16:19 UTC
The asset library says I'm about to down 7.1.0 https://godotengine.org/asset-library/asset/54

But on the plugin (and in the scene itself) it says I have 7.0.0
![image](https://user-images.githubusercontent.com/72134064/104341890-31d82600-54f2-11eb-8c2b-7c311093c784.png)

(Note: Downloaded it a minute ago using the "download" button).

**Comment by bitwes** [comment] 2021-01-14 06:16
I'm seeing this too.  I'm not sure what the problem is.  If I download the zip from the 7.1.0 release on [github](https://github.com/bitwes/Gut/releases/tag/v7.1.0) I get `7.1.0`, but if I download from the asset library (the same link you provided) then I get `7.0.0`

The printout you see when running gut is the true version.  Until I get this squared away, use the zip from github.

```
.//addons/gut/utils.gd:var version = '7.1.0'
.//addons/gut/plugin.cfg:version="7.1.0"
```

**Comment by bitwes** [comment] 2021-01-14 06:20
Had to update commit hash I think.  It should be live in a bit.

**Comment by bitwes** [comment] 2021-01-14 16:33
Fixed now.  Verified link and installing through editor.

**Closed by bitwes** 2021-01-14 16:33 UTC
Labels: bug
