### ISSUE TITLE
"Running on Devices" doesn't work when exported to .exe with embedded PCK. DirAccess.next skips files.

### ISSUE THREAD

**Issue by BlueButter-Games** [bitwes/Gut#557] opened 2024-01-23 05:57 UTC
When exported, the Gut could not see the test scripts despite having being runnable on the editor version, this was because it could not **load in the files** (Test Scripts) when its in .exe form. Below shows the screenshots:
![image](https://github.com/bitwes/Gut/assets/110042525/62efda8a-ebeb-4f51-80ca-356d916659c5)

I did some digging around and (for my case), on gut.gd -> _get_files, it uses a DirAccess.next() which seems to skip every other file except for folders on my machine.

I will note down some facts about my setup to cut-down on any potential questions:
1. I exported to windows exclusively. 
2. I have made sure to include .json files
3. It is exported as .exe with embedded PCK
4. My Godot version is 4.1.1 and GUT is 9.1.1
5. I have followed exactly the tutorial on "Running on Devices"
6. I have made sure the test scripts are there by printing out the files in the current fs_item directory

Considering this is just me following a tutorial, I am assuming others has successfully ran the tests on exported and this is a machine specific issue, has any other people have successfully done it?

**Comment by bitwes** [comment] 2024-01-23 18:40
I reproduced this (I think) on a mac.

@BlueButter-Games what appears on the settings tab in your exported game?

**Comment by BlueButter-Games** [comment] 2024-01-24 05:08
It displays the current contents of .gut_editor_config.json.

![image](https://github.com/bitwes/Gut/assets/110042525/e09d8b4f-3b59-4e50-89a9-a0a2a2ecfc97)

Here is the contents of my .gut_editor_config.json. (This is the file I use for testing, there are no other configs)

{
 "background_color": "262626ff",
 "compact_mode": false,
 "config_file": "res://.gutconfig.json",
 "dirs": [
  "res://Test"
 ],
 "disable_colors": false,
 "double_strategy": 1,
 "errors_do_not_cause_failure": false,
 "font_color": "ccccccff",
 "font_name": "CourierPrime",
 "font_size": 16,
 "gut_on_top": true,
 "hide_orphans": false,
 "ignore_pause": false,
 "include_subdirs": true,
 "inner_class": null,
 "junit_xml_file": "",
 "junit_xml_timestamp": false,
 "log_level": 1,
 "opacity": 100,
 "paint_after": 0.1,
 "panel_options": {
  "font_name": "CourierPrime",
  "font_size": 30,
  "hide_output_text": false,
  "hide_result_tree": false,
  "hide_settings": false,
  "output_font_name": "CourierPrime",
  "output_font_size": 30,
  "use_colors": false
 },
 "post_run_script": "",
 "pre_run_script": "",
 "prefix": "test_",
 "selected": null,
 "should_exit": true,
 "should_exit_on_success": true,
 "should_maximize": false,
 "show_help": false,
 "suffix": ".gd",
 "tests": [],
 "unit_test_name": null
}

**Comment by BlueButter-Games** [comment] 2024-01-24 05:10
Since we're talking about configs, You might want to know in my Parent to GutControl, it overrides these config settings only  (These were in the copy pasted "Running on Devices".)

![image](https://github.com/bitwes/Gut/assets/110042525/7e66d43d-dc3b-4333-9f36-934e85e0d092)

**Comment by bitwes** [comment] 2024-01-24 21:12
It appears that a `DirAccess` instance's `file_exists` returns `false` for exported projects but `FileAccess.file_exists` does not.  I think this is fixed in the [i557 branch](https://github.com/bitwes/Gut/tree/i557).  It looks like there are some font issues, but I got tests to run on an exported project.

**Comment by bitwes** [comment] 2024-01-25 15:28
Created an [issue](https://github.com/godotengine/godot/issues/87552) for this in the engine.

**Comment by bitwes** [comment] 2024-02-08 00:47
Fixed in 9.2

**Closed by bitwes** 2024-02-08 00:47 UTC
Labels: bug
