### ISSUE TITLE
Feature request: partial doubles

### ISSUE THREAD

**Issue by nightblade9** [bitwes/Gut#115] opened 2019-04-22 00:38 UTC
I come from a C# background. We use `Moq` a lot for mocks/doubles. It allows you to create *partial mocks* as well, meaning: create a mock/double of this class, *retaining all functionality except what you explicitly override.* 

I would like to use this in Gut also; although, currently, I can probably use a work-around like breaking a function into smaller pieces and just testing those instead.

Partial mocks might look something like this:

```
double partial_mocked = double("res://scripts/Monster.gd").new().partial_mock()
stub(partial_mocked, "expensive_calculation").to_return(17)
var actual = partial_mocked.secret_value() # calls expensive_calculation and doubles it
assert_eq(34, actual)
```

In my case, I have a wrapper function that calls a second function, which I want to stub out; I don't want to stub out the entire instance.

**Comment by bitwes** [comment] 2019-04-22 01:23
I think this is high on the list for the next major enhancement.  Issue #98 is closely related to this and partial mocks would probably be the best way to implement it.  The latest release has some features that should make this easier to do under the covers.

I think it would have to look a little more like this though based on how the doubling works:
```
double partial_mocked = double_partial("res://scripts/Monster.gd").new()
stub(partial_mocked, "expensive_calculation").to_return(17)
var actual = partial_mocked.secret_value() # calls expensive_calculation and doubles it
assert_eq(34, actual)
```

As mentioned in #98 I've been thinking about adding a stub that will cause a method to punch through to the super method.  The `double_partial` would just be setup to do this by default for all methods.  With both of these in place you can stub a few methods or have just a few methods not stubbed fairly easily.

It's now on the list.  Good suggestion.

**Comment by nightblade9** [comment] 2019-04-22 01:47
That sounds like a great proposal. I look forward to trying it out in the next release!

**Comment by bitwes** [comment] 2019-05-26 19:46
I've implemented this in the next release branch currently named `v6.7.1`.  I've tested it, but I haven't dog-fooded it yet.  Any testing/feedback would be greatly appreciated.

I haven't done the documentation for it yet, but it works the way you would expect.  More info can be found in the CHANGES.MD for the branch:  https://github.com/bitwes/Gut/blob/v6.7.1/CHANGES.md

**Comment by nightblade9** [comment] 2019-05-27 17:18
I'm not very experienced with Godot plugins and don't see any instructions for this - how do I "build" Gut or switch temporarily to a GitHub version so I can try this out?

My current project (which I requested this for) is very nearly completed, but since I requested this feature, I will add a few tests with it so you can get at least some feedback on it.

**Comment by bitwes** [comment] 2019-05-28 04:33
Yea, without making a release it isn't intuitive.  If you can help out, that's great. I just figured I'd try to get it in front of some people first and get some early feedback.

Steps to install:
1.  Clone down the branch.
1.  Copy the addons/gut folder into your project overwriting the existing one.
1.  That should do it.  Everything should line up.  I probably wouldn't have Godot running at the time you do it, but even that shouldn't matter for this release.

To revert to the previous version I think you can just uninstall the plugin and reinstall.  If for some reason that doesn't work, just blow away `addons/gut` in your project and reinstall the plugin.

As a side note, non-engine plugins are just GDScripts that follow a convention.  There's a config file, a place to put them (`addons`), and a "main" script which the config files points to.

**Comment by nightblade9** [comment] 2019-05-28 08:53
I seem to be having some trouble with the constructor. If I have a script file like so:

```
# item.gd
func _init(target):
  self.target = target
```

I should be able to create a double like so:

```
var item = partial_double("res://.../item.gd").new(17)
```

Instead -- irrespective of any arguments I pass (or even with none) -- I get this error:

`doubler.gd:79: Invalid call to function 'new' in base 'GDScript'. Expected 1 arguments.`

This is the code it's complaining about:

```
# Returns an instance of the class/inner class
func instantiate():
    return get_loaded_class().new()
```

I think you need to change this to something like:

```
func instantiate(args):
  return get_loaded_class().new(args)
```

Not sure how to make that play nicely with instances that don't require args (can you pass null?)

**Comment by nightblade9** [comment] 2019-05-28 14:49
My bad. Actually, it's perfectly legitimate to say "this only works with classes that have parameterless constructors." I'm thinking of C#, where they have sufficient reflection support to write code like "give me an arbitrary list of parameters of various types, and I can figure out which constructor takes those types."

I will rewire my class slightly to make it work, or find a different class to test. My original code that I wanted to test, is not easy to test/mock, because it's static.

**Comment by nightblade9** [comment] 2019-05-28 17:26
OK, I got this working. It looks good as far as I can tell - I can create partial doubles, stub out calls, spy, yield, etc. and everything works as I expected.

You can close this issue - as far as I'm concerned, it's :100:

**Comment by bitwes** [comment] 2019-05-28 19:26
Great!  Thanks for the help.  I'll close it out when the release is done.

About the parameters to new.  The problem is that I can't overload new, so
it gets really really hairy trying to get values to it.

As you found out, it was blowing up when I make a new instance to find all
methods.  Godot has a lot of tools that let me inspect the object and that
is way easier than actually parsing the gdscript.  Glad you figured it
out.  If you have any feedback on the help files I'd love to hear it.  Just
open up a new issue.

**Comment by bitwes** [comment] 2019-06-06 01:12
Partial doubles have been implemented in 6.8.0.   Check out the partial doubles wiki page for more information.

**Closed by bitwes** 2019-06-06 01:12 UTC
Labels: enhancement

**Comment by 8nouk** [comment] 2020-03-01 16:14
@nightblade9 So if I understood correctly, passing arguments to a constructor of a partial double is impossible due to the GDScript design ?

**Comment by bitwes** [comment] 2020-03-01 17:59
This is due to the implementation of GUT and not GDScript.  Instead of writing a parser for GDScript I chose to use the metatdata that Godot provides.  The only way to get this metadata though is to create an instance of the object.  Whenever you double something, GUT makes a new instance of it, gets all the method signatures and creates a new class that extends that one but has all the hooks for spying and mocking built in.
