### ISSUE TITLE
Big leaks of memory/nodes when using Gut

### ISSUE THREAD

**Issue by qarmin** [bitwes/Gut#146] opened 2020-02-23 10:20 UTC
Simple running of default scene leaks a lot of nodes which should be deleted.
Every single node which is removed from scene tree needs to be deleted with `queue_free` or `free` and every other object with `free` 

Orphan nodes monitor is good to show how many nodes leaks

![Zrzut ekranu z 2020-02-23 11-14-00](https://user-images.githubusercontent.com/41945903/75110413-3ec7fe80-562e-11ea-95a9-656261b27539.png)

To reproduce leak, just run Godot with -v flag e.g `godot -v`, run tests and close Godot, then to terminal will be printed a lot of info about leaking nodes.

e.g.:
```
Leaked instance: Reference:3107
Leaked instance: GDScript:1195 - Resource name:  Path: res://addons/gut/one_to_many.gd
Leaked instance: Reference:2226
Leaked instance: GDScript:1191 - Resource name:  Path: res://addons/gut/test_collector.gd
Leaked instance: GDScript:3303 - Resource name:  Path: 
Leaked instance: Node2D:2106 - Node name: 
Leaked instance: GDScript:1194 - Resource name:  Path: res://addons/gut/thing_counter.gd
Leaked instance: GDScript:1675 - Resource name:  Path: res://test/resources/doubler_test_objects/double_extends_node2d.gd
Leaked instance: Reference:1710
Leaked instance: GDScript:2881 - Resource name:  Path: 
Leaked instance: Reference:2229
Leaked instance: _File:2859
Leaked instance: Reference:3309
Leaked instance: GDScript:3386 - Resource name:  Path: res://test/resources/replace_node_scenes/arena.gd
Leaked instance: _File:3442
Leaked instance: Node2D:1306 - Node name: 
Leaked instance: Node2D:3023 - Node name: 
```

**Comment by bitwes** [comment] 2020-02-23 21:17
This is a duplicate of #122.  I'm going to add some comments to that one.  If you have any suggestions please add them there.

**Closed by bitwes** 2020-02-23 21:17 UTC
