### ISSUE TITLE
Area2D body_entered + custom signal not firing

### ISSUE THREAD

**Issue by nightblade9** [bitwes/Gut#220] opened 2020-09-26 02:22 UTC
I have two classes, Player and Monster. Both have an Area2D. The Monster class has an event connect set up in the GUI; if it overlaps with the player, it emits the `battle_started` signal.

Here's my code, which works fine outside of Gut (in a regular scene with asserts removed) - it prints `!`

```

func _ready():
	var m = Monster.instance()
	#watch_signals(m)
	add_child(m)
	m.connect("start_battle", self, "_on_start_battle")
	m.position = Vector2(100, 100)
	
	var player = Player.instance()
	
	add_child(player)
	
	player.position = m.position

func _on_start_battle(who):
	print("!")
```

When I put it into a Gut test, uncomment `watch_signals` and add `assert_signal_emitted(m, "start_battle")` it fails.

I suspect it's something to do with how Godot itself processes signals, and what the "requirements" are to execute the code that would handle this. I thought calling `gut.simulate(m, 10, 1)` or similar calls on `player` or `self` (or adding a `Node2D` scene, adding all objects to that, and calling simulate on that) might trigger it, but alas, no.

The tests for signals all handle adding the signal via code, so I'm not sure if this is supported or if I'm doing something wrong. It's probably easily reproducible by creating a scene with an Area2D, wiring up the signal in the UI, and then adding bodies to trigger it.

**Comment by bitwes** [comment] 2020-09-26 03:43
For collisions to happen you have to put a yield in so that they get
processed.  Check out this wiki page for more details:.
https://github.com/bitwes/Gut/wiki/Yielding

**Comment by nightblade9** [comment] 2020-09-26 04:00
Interesting - `yield(m, "start_battle")` works but `yield(yield_to(m, "start_battle", n))` waits for `n` seconds and then times out and fails.

**Comment by bitwes** [comment] 2020-09-26 06:40
You are missing the `YIELD` constant provided by `test.gd` as the 2nd parameter to `yield`.  This should work:
```
yield(yield_to(m, "start_battle", n), YIELD)
```
I didn't think that 2nd parameter was optional.  What  happens is that  `yield_to` will return the GUT instance so `yield` has an  object to yield to.   The 2nd parameter  is a  constant for the  name of the signal that GUT emits when either it detects that the signal is emitted or n seconds elapses.

The final test might look something like this (added in some extras):
```
func test_battle_starts_on_collision():
	# add_child_autofree adds the child and autofrees instance  after 
	# the test for less  orphans, it returns whatever is passed in.
	# https://github.com/bitwes/Gut/wiki/Memory-Management
	var m = add_child_autofree(Monster.instance()) 
	watch_signals(m) # technically optional since yield_to does this  but it  doesn't hurt.
	m.position = Vector2(100, 100)
	
	var player = add_child_autofree(Player.instance())	
	player.position = m.position
	
	var n = 5
	yield(yield_to(m, "start_battle", n), YIELD)
	assert_signal_emitted(m, "start_battle")
```

**Comment by nightblade9** [comment] 2020-09-26 15:38
I pasted my code wrong. It crashes without `YIELD`, and with `YIELD` it just times out and the assert that the signal was emitted, fails.

**Comment by bitwes** [comment] 2020-09-28 18:09
Are you sure the signal is being fired?  Can you post some relevant code and the test?

**Comment by nightblade9** [comment] 2020-09-28 18:24
I am 100% sure the signal is being fired, because it works with `yield(m, "start_battle")` but not `yield(yield_to(m, "start_battle", n), YIELD)`.  

I'll see if I can create a minimal project that reproduces the problem.

**Comment by bitwes** [comment] 2021-01-14 17:15
Does your signal by chance take parameters?  I found #258 while testing my game.

**Comment by bitwes** [comment] 2021-01-14 17:22
Closing, this appears to be caused by #258.

**Closed by bitwes** 2021-01-14 17:22 UTC
