### ISSUE TITLE
is_version_ok seems incorrect when major/minor is increased

### ISSUE THREAD

**Issue by touilleMan** [bitwes/Gut#232] opened 2020-10-19 20:47 UTC
https://github.com/bitwes/Gut/blob/557493eab3e4df187ea26c09064d30c9f92b83d8/addons/gut/utils.gd#L130-L135

This code seems wrong when the major/minor version is incremented:
- `req_godot == [3, 2, 3]` and `info == [3, 3, 0]`
- `req_godot == [3, 1, 0]` and `info == [4, 0, 0]`

Both example end up with `is_version_ok` returning false when it would be expected to be true.

As a matter of fact I'm not 100% sure it's a bug or an expected behavior (it's understandable that compatible with Godot 3.2.0 doesn't means compatible with Godot 4)...
So `req_godot` might stand for "The minimal version of Godot compatible, only considering higher patch version as compatible" but then it would be much better to write the test as `req_godot.major == info.major and req_godot.minor == info.major and req_godot.patch <= info.patch`

**Comment by bitwes** [comment] 2020-10-22 17:36
Good find.  The check was intended to be the minimum version of Godot that GUT supports.  It should be conditionally  checking minor version if major is same and patch if major/minor is the same.  I've changed  the method signature to be testable and added  some failing tests in the `issue_232_version_check` branch.  I'll come back to this shortly if nobody else picks it up in the meantime.

Right  now the minimum version required is `3.2.0`.  This shouldn't be a problem in the immediate future but should be fixed soon.  The  next release that could cause a problem right now would  be `4.0.0`, or if GUT requires a patch version for some reason and there is a minor bump that happens after (such as the first example given).

**Closed** 2020-11-02 21:49 UTC
Labels: bug
