### ISSUE TITLE
test function with the same prefix will also get executed 

### ISSUE THREAD

**Issue by a-irsyad** [bitwes/Gut#611] opened 2024-05-27 05:19 UTC
# Versions
* Godot: 4.2.2
* GUT: 9.2.1
* OS: openSUSE Tumbleweed 20240523 x86_64

# The Bug
Other test functions are also get executed **if it has the same prefix with the test being run**

# Steps To Reproduce

1. Create a simple test script then paste the code below:

```gdscript
extends GutTest

func test_A():
	print("A");
	assert_eq(true, true);
	
func test_AB():
	print("AB");
	assert_eq(true, true);

func test_ABC():
	print("ABC");
	assert_eq(true, true);
```

2. Run **ONLY** `test_A()` .
3. Check the "output" console. You will notice that `test_AB()` and `test_ABC()` also get executed despite you didn't intend to run it.

**Comment by bitwes** [comment] 2024-05-29 14:51
This is a duplicate of #366.  GUT runs all tests that contain the string passed to it by the Play buttons.  This happens with script names as well.

**Closed by bitwes** 2024-05-29 14:51 UTC
